SDPIComponents.i18n.locales = {
  en: {
    PickHome: "Select a home",
    HomeLabel: "Home",
    HomeFetchingLabel: "Fetching homes...",
    PickZone: "Select a zone",
    ZoneLabel: "Zone",
    ZoneFetchingLabel: "Fetching zones...",
    UnitLabel: "Unit",
    PickUnit: "Select a unit",
    Celsius: "Celsius",
    Fahrenheit: "Fahrenheit",
    TemperatureLabel: "Temperature",
    TemperatureSelectedLabel: "Selected temperature",
    PresetNameLabel: "Preset Name",
    PresetNamePlaceholder: "e.g. Heat On",
    TerminationLabel: "Duration",
    TerminationManual: "Until changed",
    TerminationNextBlock: "Until next schedule block",
    TerminationTimed: "Timed (30 min)",
    PresenceLabel: "Presence",
  },
  de: {
    PickHome: "Zuhause auswählen",
    HomeLabel: "Zuhause",
    HomeFetchingLabel: "Lade Zuhause...",
    PickZone: "Zone auswählen",
    ZoneLabel: "Zone",
    ZoneFetchingLabel: "Lade Zonen...",
    UnitLabel: "Einheit",
    PickUnit: "Einheit auswählen",
    Celsius: "Celsius",
    Fahrenheit: "Fahrenheit",
    TemperatureLabel: "Temperatur",
    TemperatureSelectedLabel: "Gewählte Temperatur",
    PresetNameLabel: "Voreinstellungsname",
    PresetNamePlaceholder: "z.B. Heizung An",
    TerminationLabel: "Dauer",
    TerminationManual: "Bis zur Änderung",
    TerminationNextBlock: "Bis zum nächsten Zeitblock",
    TerminationTimed: "Zeitgesteuert (30 Min.)",
    PresenceLabel: "Anwesenheit",
  },
  fr: {
    PickHome: "Choisissez une maison",
    HomeLabel: "Maison",
    HomeFetchingLabel: "Chargement des maisons...",
    PickZone: "Choisissez une pièce",
    ZoneLabel: "Pièce",
    ZoneFetchingLabel: "Chargement des pièces...",
    UnitLabel: "Unité",
    PickUnit: "Choisissez une unité",
    Celsius: "Celsius",
    Fahrenheit: "Fahrenheit",
    TemperatureLabel: "Température",
    TemperatureSelectedLabel: "Température sélectionnée",
    PresetNameLabel: "Nom du préréglage",
    PresetNamePlaceholder: "ex. Chauffage On",
    TerminationLabel: "Durée",
    TerminationManual: "Jusqu'au changement",
    TerminationNextBlock: "Jusqu'au prochain bloc horaire",
    TerminationTimed: "Minuté (30 min)",
    PresenceLabel: "Présence",
  },
  es: {
    PickHome: "Selecciona una casa",
    HomeLabel: "Casa",
    HomeFetchingLabel: "Cargando casas...",
    PickZone: "Selecciona una habitación",
    ZoneLabel: "Habitación",
    ZoneFetchingLabel: "Cargando habitaciones...",
    UnitLabel: "Unidad",
    PickUnit: "Selecciona una unidad",
    Celsius: "Celsius",
    Fahrenheit: "Fahrenheit",
    TemperatureLabel: "Temperatura",
    TemperatureSelectedLabel: "Temperatura seleccionada",
    PresetNameLabel: "Nombre del ajuste",
    PresetNamePlaceholder: "ej. Calefacción On",
    TerminationLabel: "Duración",
    TerminationManual: "Hasta cambio",
    TerminationNextBlock: "Hasta el siguiente bloque horario",
    TerminationTimed: "Temporizado (30 min)",
    PresenceLabel: "Presencia",
  },
};

// Auto-detect and set language
(async function () {
  try {
    const info = await SDPIComponents.streamDeckClient.getConnectionInfo();
    SDPIComponents.i18n.language = info.info.application.language;
  } catch (e) {
    console.warn("Could not detect language, defaulting to English");
  }
})();
